### PR TITLE
Switches to prompts from prompt

### LINKED ISSUE #35: Dependency (winston) breaks on node 14.x
Winston 2.x doesn't work with node 14.x. and thus breaks this tool.

https://github.com/winstonjs/winston/issues/1797

```
 Apostrophe  create-project  Failed
(node:75963) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object.exports.setLevels (/Users/kyron/.nvm/versions/node/v14.4.0/lib/node_modules/apostrophe-cli/node_modules/winston/lib/winston/common.js:32:14)
    at Object.<anonymous> (/Users/kyron/.nvm/versions/node/v14.4.0/lib/node_modules/apostrophe-cli/node_modules/winston/lib/winston.js:83:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
```

For now I've downgraded my node version to 13.x and it's working fine.

### PR DESCRIPTION
**Pull request by abea**
There's an "s," so it's better.

Fixes #35, a Node 14 bug report.

### CODE REVIEW

File: lib/commands/create.js [hunk 1]
```diff
@@ -47,25 +47,19 @@ module.exports = function (program) {
...
-          if (err) {
-            util.error('create');
-            return false;
-          }
-          exec('echo "' + result.password + '" | node app.js apostrophe-users:add admin admin');
-          util.nlog('create', 'Login as "admin"');
-          util.success('create-project');
-          return true;
+
+        const response = await prompts({
```
Comment (boutell) [inline lib/commands/create.js:51]: It's a lot better!

**Review by boutell — APPROVED** [review]
